name       : mu
version    : 1.6.10
release    : 2
source     :
    - https://github.com/djcb/mu/releases/download/1.6.10/mu-1.6.10.tar.xz : 0bc224aab2bfe40b5209af14e0982e637789292b7979872658d4498b29e900b6
license    : GPL-3.0-only
component  : editor
summary    : maildir indexer/searcher + emacs mail client + guile bindings
description: |
    mu is a tool for dealing with e-mail messages stored in the Maildir-format. mu’s purpose in life is to help you to quickly find the messages you need; in addition, it allows you to view messages, extract attachments, create new maildirs, and so on. See the mu cheatsheet for some examples. mu is fully documented.
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(gmime-3.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(guile-2.0)
    - pkgconfig(webkit2gtk-4.0)
    - pkgconfig(xapian-core)
    - emacs
setup      : |
    %configure
build      : |
    %make
    emacs --batch --eval '(byte-recompile-directory "mu4e")'
install    : |
    %make_install
